### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor

### ISSUE THREAD

**Issue by shubsaini09** [mergermarket/acuris-aws-es-connection#70]
Using the same code given in the document throws below error

```
TypeError: Class extends value undefined is not a constructor or null
at generateAWSConnectionClass (/var/task/node_modules/@acuris/aws-es-connection/dist/index.js:10:56)
at createAWSConnection (/var/task/node_modules/@acuris/aws-es-connection/dist/index.js:51:21)
at getESClient (/var/task/index.js:20:25)
at async exports.handler (/var/task/index.js:38:27)
```
my dependecies

```
"dependencies": {
    "@acuris/aws-es-connection": "^2.3.0",
    "@elastic/elasticsearch": "^8.11.0"
  }
```
`const awsCredentials = await awsGetCredentials();` returns the credentials successfully but it fails in `const AWSConnection = createAWSConnection(awsCredentials);`

can you help resolve this issue?

**Comment by chrisLoef** [comment]
@shubsaini09 did you find any solution for this?

**Comment by MichaelPooleLF** [comment]
From my review, the AWSConnection class is trying to extend off of "Connection". In newer versions of elasticsearch, "Connection" is a Type, not a class. Probably have to change this to extend based on one of the classes listed in that type.

**Comment by tomchiverton** [comment]
Such as ?
